name: github k8s image sync
description: An action for Kubernetes gcr.io image Sync
author: wangjia_1919@163.com
branding:
  color: blue
  icon: code
inputs:
  token:
    description: 'Token used to login docker registry'
    required: true
  username:
    description: 'Username used to login docker registry'
    required: true
  registry:
    description: 'Docker registry server address'
    required: false
    default: ''
  repository:
    description: 'Docker image repository name'
    required: true
  kubernetes_version:
    description: 'Set kubernetes version'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'