name: github k8s image sync
description: An action for Kubernetes gcr.io image Sync
author: wangjia_1919@163.com
branding:
  color: blue
  icon: code
inputs:
  token:
    description: 'Token used to login github docker package'
    required: true
  username:
    description: 'Username used to login github docker package'
    required: true
  password:
    description: 'Password used to login docker registry'
    required: true
  registry:
    description: 'Github docker package registry server address'
    required: false
    default: 'docker.pkg.github.com'
  repository:
    description: 'Github docker package repository name'
    required: true
    default: ''
  kubernetes_version:
    description: 'Set kubernetes version'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'